#! /bin/sh

bspc config border_width        2 
bspc config window_gap          40

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

# Color of the border of an urgent window.
bspc config urgent_border_color "red"

# Color of the border of a focused window of a focused monitor.
bspc config focused_border_color "#87DFFA"

# Color of the bordeR of a focused window of an unfocused monitor.
bspc config active_border_color "#222222"

# Color of the border of an unfocused window.
bspc config normal_border_color "#222222"

# Color of the presel message feedback.
bspc config presel_border_color "#9B59B6"

#bspc monitor -d I II III IV V VI VII VIII IX X

bspc monitor DP-0 -d • • • 	
bspc monitor HDMI-0 -d • • •
bspc monitor DVI-I-1 -d • • •

bspc monitor ^1 -s ^2

bspc rule -a Gimp desktop=^5 follow=on floating=on
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

panel &
