set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" Github repos
Plugin 'itchyny/lightline.vim'
Plugin 'cakebaker/scss-syntax.vim'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

au! FileType css,scss setl iskeyword+=-

:set laststatus=2
:nmap <C-N> :set invnumber<CR>
:set cursorline
:set noshowmode

":set shiftwidth=4
":set expandtab

:set sts=4
:set sw=4
:set ts=8
:set expandtab

:set nowrap
:set autoindent

syntax on

:hi MatchParen ctermbg=2 ctermfg=235
:hi Visual ctermbg=4
:hi Error ctermfg=196  ctermbg=2
:hi CursorLine cterm=bold ctermbg=4
:hi CursorLineNr ctermfg=255 
"Light gray
:hi Comment ctermfg=12
"Blue
:hi Statement ctermfg=5
"Light gray
:hi Constant ctermfg=246

:hi Identifier ctermfg=1

:hi Type ctermfg=2
"Dark gray
:hi htmlTag ctermfg=5
"Dark gray
:hi htmlEndTag ctermfg=5
:hi LineNr ctermfg=12
:hi htmlTitle ctermfg=255

:hi sassClass ctermfg=6
:hi sassClassChar ctermfg=6
:hi sassId ctermfg=6
:hi sassIdChar ctermfg=6

:hi scssProperty ctermfg=2
:hi scssAttribute ctermfg=246
